/**
 * Tokenized Voucher — server-side HMAC token generation for QR codes.
 *
 * The QR encodes: `barcode|timestamp|hmac`
 * - Tokens are generated by the `generate-voucher-token` Edge Function (HMAC-SHA256)
 * - Tokens rotate every 60s; staff scanner validates via `validate-voucher-token` Edge Function
 * - No secrets are stored client-side
 */

import { supabase } from '@/lib/supabase';
import { getEnhancedFingerprint, getOrCreateDeviceId } from '@/lib/deviceId';

export const TOKEN_ROTATE_INTERVAL = 30_000; // 30 seconds — tightened from 60s to reduce replay window

// ─── Server-side token generation ──────────────────────────────────

/**
 * Request a signed QR token from the server for a voucher.
 * The server verifies ownership and returns an HMAC-SHA256 signed payload.
 * Includes device fingerprint for anti-screenshot binding.
 */
export async function generateTokenizedPayload(voucherId: string): Promise<string> {
  // Include enhanced device fingerprint (hardware signals + random ID)
  // so the server can bind the token to this specific device
  let deviceFingerprint: string | undefined;
  try {
    deviceFingerprint = await getEnhancedFingerprint();
  } catch {
    // Fallback to basic device ID if enhanced fingerprint fails
    try {
      deviceFingerprint = await getOrCreateDeviceId();
    } catch {
      // If device ID unavailable, proceed without it (server will still work)
    }
  }

  const { data, error } = await supabase.functions.invoke('generate-voucher-token', {
    body: {
      voucher_id: voucherId,
      device_fingerprint: deviceFingerprint,
    },
  });

  if (error) throw new Error(`Token generation failed: ${error.message}`);
  if (!data?.token) throw new Error('No token returned from server');

  return data.token;
}

// ─── Server-side token validation (staff scanner) ──────────────────

/**
 * Validate a scanned QR token via the server Edge Function.
 * Only staff with proper roles can call this.
 */
export async function validateTokenizedPayload(qrPayload: string): Promise<{
  valid: boolean;
  error?: 'invalid_format' | 'expired' | 'invalid_token' | 'not_found' | 'already_redeemed' | 'invalid_status';
  voucher?: {
    barcode: string;
    title: string;
    description: string;
    type: string;
    value?: number;
    expires_at?: string;
  };
}> {
  const { data, error } = await supabase.functions.invoke('validate-voucher-token', {
    body: { qr_payload: qrPayload },
  });

  if (error) {
    // Network error or rate limited
    throw new Error(`Token validation failed: ${error.message}`);
  }

  return data;
}

/**
 * Extract the barcode from a QR payload without validating the token.
 * Used only for display purposes (e.g., showing the barcode text below the QR code).
 * NEVER use this for authorization decisions.
 */
export function extractBarcodeFromPayload(payload: string): string | null {
  const parts = payload.split('|');
  if (parts.length >= 1 && parts[0].startsWith('VCH-')) {
    return parts[0];
  }
  return null;
}
