import { supabase } from '@/lib/supabase';
import { Voucher, VoucherType, VoucherStatus } from '@/types';

// ─── DB row type ─────────────────────────────────────────────
type VoucherRow = {
  id: string;
  user_id: string;
  type: VoucherType;
  status: VoucherStatus;
  title: string;
  description: string;
  value: number | null;
  barcode: string;
  source: string;
  created_at: string;
  expires_at: string | null;
  redeemed_at: string | null;
  redeemed_by: string | null;
  redemption_nonce: string | null;
  order_id: string | null;
};

// ─── Result types ────────────────────────────────────────────
export type ValidationResult = {
  valid: boolean;
  error?: 'not_found' | 'already_redeemed' | 'expired' | 'invalid_status';
  redeemed_at?: string;
  voucher?: Voucher;
};

export type RedemptionResult = {
  success: boolean;
  error?: 'not_found' | 'already_redeemed' | 'expired' | 'invalid_status';
  voucher?: Voucher;
};

export type CreateVoucherParams = {
  userId: string;
  type: VoucherType;
  title: string;
  description?: string;
  value?: number;
  source?: string;
  expiresAt?: string;
};

// ─── Helpers ─────────────────────────────────────────────────

function rowToVoucher(row: VoucherRow): Voucher {
  return {
    id: row.id,
    type: row.type,
    status: row.status,
    title: row.title,
    description: row.description,
    value: row.value ?? undefined,
    barcode: row.barcode,
    source: row.source,
    earnedAt: row.created_at,
    redeemedAt: row.redeemed_at ?? undefined,
    expiresAt: row.expires_at ?? undefined,
    redeemedBy: row.redeemed_by ?? undefined,
  };
}

// ─── Public API ──────────────────────────────────────────────

/**
 * Create a voucher server-side (barcode generated by PostgreSQL).
 */
export async function createVoucher(params: CreateVoucherParams): Promise<Voucher> {
  const { data, error } = await supabase.rpc('create_voucher', {
    p_user_id: params.userId,
    p_type: params.type,
    p_title: params.title,
    p_description: params.description ?? '',
    p_value: params.value ?? null,
    p_source: params.source ?? 'system',
    p_expires_at: params.expiresAt ?? null,
  });

  if (error) throw error;

  const result = data as { success: boolean; voucher: VoucherRow };
  if (!result.success) throw new Error('Failed to create voucher');

  return rowToVoucher(result.voucher);
}

/**
 * Fetch all vouchers for a customer — newest first.
 */
export async function fetchUserVouchers(userId: string): Promise<Voucher[]> {
  const { data, error } = await supabase
    .from('vouchers')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false });

  if (error) throw error;
  return (data as VoucherRow[]).map(rowToVoucher);
}

/**
 * Validate a voucher by barcode (read-only, no state change).
 * Used by staff scanner to preview before redeeming.
 */
export async function validateVoucher(barcode: string): Promise<ValidationResult> {
  const { data, error } = await supabase.rpc('validate_voucher', {
    p_barcode: barcode,
  });

  if (error) throw error;

  const result = data as {
    valid: boolean;
    error?: string;
    redeemed_at?: string;
    voucher?: VoucherRow;
  };

  return {
    valid: result.valid,
    error: result.error as ValidationResult['error'],
    redeemed_at: result.redeemed_at,
    voucher: result.voucher ? rowToVoucher(result.voucher) : undefined,
  };
}

/**
 * Atomically redeem a voucher. Prevents double-spending at the DB level.
 * Only one concurrent call per barcode can succeed.
 */
export async function redeemVoucher(
  barcode: string,
  staffId?: string
): Promise<RedemptionResult> {
  const { data, error } = await supabase.rpc('redeem_voucher', {
    p_barcode: barcode,
    p_staff_id: staffId ?? null,
  });

  if (error) throw error;

  const result = data as {
    success: boolean;
    error?: string;
    voucher?: VoucherRow;
  };

  return {
    success: result.success,
    error: result.error as RedemptionResult['error'],
    voucher: result.voucher ? rowToVoucher(result.voucher) : undefined,
  };
}

/**
 * Subscribe to real-time voucher changes for a specific user.
 * Returns an unsubscribe function.
 */
export function subscribeToVouchers(
  userId: string,
  onInsert: (voucher: Voucher) => void,
  onUpdate: (voucher: Voucher) => void
) {
  const channel = supabase
    .channel(`vouchers-${userId}`)
    .on(
      'postgres_changes',
      {
        event: 'INSERT',
        schema: 'public',
        table: 'vouchers',
        filter: `user_id=eq.${userId}`,
      },
      (payload) => {
        onInsert(rowToVoucher(payload.new as VoucherRow));
      }
    )
    .on(
      'postgres_changes',
      {
        event: 'UPDATE',
        schema: 'public',
        table: 'vouchers',
        filter: `user_id=eq.${userId}`,
      },
      (payload) => {
        onUpdate(rowToVoucher(payload.new as VoucherRow));
      }
    )
    .subscribe();

  return () => {
    supabase.removeChannel(channel);
  };
}
